FROM python:3.12-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir kafka-python==2.2.15
COPY consumer ./consumer

ENV PYTHONUNBUFFERED=1
CMD ["python", "-m", "consumer.consumer"]